//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Flight_Reservation = new HashSet<Flight_Reservation>();
        }
    
        public int id { get; set; }
        public Nullable<int> flight_number { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> flight_date { get; set; }
        public Nullable<decimal> duration { get; set; }
        public string airport_id { get; set; }
        public string airline_id { get; set; }
        public string aircraft_id { get; set; }
        public Nullable<decimal> stopover_duration { get; set; }
        public string via { get; set; }
        public Nullable<int> available_seats { get; set; }
        public Nullable<int> allowedd_buggage_weight { get; set; }
        public Nullable<decimal> econ_price { get; set; }
        public Nullable<decimal> bus_price { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Reservation> Flight_Reservation { get; set; }
    }
}
