//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerary
    {
        public string Flight { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Aircraft { get; set; }
        public string Status { get; set; }
        public string Passenger_Name { get; set; }
        public string Ticket_Number { get; set; }
        public string Flyer_Number { get; set; }
        public string Special_Needs { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Currency { get; set; }
        public int id { get; set; }
    }
}
