//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooker.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger()
        {
            this.Passenger_Reservation = new HashSet<Passenger_Reservation>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "First Name is required")]
        public string first_name { get; set; }
        [Required(ErrorMessage = "Last Name is required")]
        public string last_name { get; set; }
        [Required(ErrorMessage = "Phone Number is required")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Passport Number is required")]
        public string passport_number { get; set; }
        public string Age_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger_Reservation> Passenger_Reservation { get; set; }
    }
}
