//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportView
    {
        public Nullable<int> Flight_No { get; set; }
        public int Reservation_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
